server:
  port: 8080
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
    include-message: always

logging:
  level:
    root: INFO
    com.ted.micro: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: mongodb
