version: '2.1'

services:
  product:
    build: product-server
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommend:
    build: recommend-server
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    build: review-server
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  integrated:
    build: integrated-api
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
